export const coursedetails = {
  title: "Master in Technical Analysis & Trading",
  aboutCourse: "",
  contents: [
    "Basics of Stock market",
    "Technical Indicators and Stratgies",
    "Identification of Trend",
    "Price action strategy",
    "Intraday Trading strategy",
    "Pattern Identification",
    "Risk Management",
  ],
  price: "Rs.2499/- ",
  features: [
    "Anytime access of the course from anywhere in the world.",
    "Our trainers are not just trainers they all are Profitable Traders.",
    "Premium community of best quality traders.",
    "Technical analysis is not only useful for stock trading, you can also use it for analysing commodity future & options and crypto trading.",
    "Support center for doubt solving sessions.",
    "Learn in you comfortable language.",
  ],
  module1: [
    "Basics of Stock Market",
    "Basics of Technical analysis and assumptions",
  ],
  module2: [
    "Charts Patterns",
    "Trends - Uptrend, Downtrend, Sideways",
    "Supply and Demand",
    "Support and Resistance (Basics)",
  ],
  module3: [
    "Candlestick Charts",
    "Bullish & bearish candles",
    "Various types of candles",
    "Candlestick patterns",
  ],
  module4: [
    "Static support levels",
    "Static resistance levels",
    "Dynamic support levels",
    "Dynamic resistance levels",
  ],
  module5: ["Simple moving average", "Exponential moving average"],
  module6: ["Swing Trading", "Breakout Trading"],
  module7: [
    "Trend continuation patterns",
    "Reversal Patterns",
    "Bilateral patterns",
  ],
  module8: ["Moving averages", "RSI", "Pivot points", "CPR"],
  module9: [
    "Trading Setup",
    "Identifying entry and exit levels",
    "Risk management",
    "Revision",
  ],
  module10: ["Trade Analysis", "Live Trading"],
};
